   // Some global parameters for a typical aircraft
   // Add your own specific ones here.
   // Include in all the  scripts you create in project
   // so they are all using the same values for these
   // Assume model is of the floor, facing to the right
   String projectpath = "<PROJPATH>" ;

   // String thats used to generate the display label
   string DisplayLabel="<PROJNAME>";
   
   // scaling things may reduce them below the minimum size that we can practically print
   // Set a limit. Set to 0 if you dont want a limit at all.
   Double minimumDimension = 0.5;